package io.github.fossure.web.rest.v1;

import io.github.fossure.domain.LibraryErrorLog;
import io.github.fossure.repository.LibraryErrorLogCustomRepository;
import io.github.fossure.service.LibraryErrorLogCustomService;
import io.github.fossure.service.LibraryErrorLogQueryCustomService;
import io.github.fossure.web.rest.LibraryErrorLogResource;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

/**
 * Custom REST controller for managing {@link LibraryErrorLog}
 * where changes are inserted that are different from the base class generated by the JHipster generator.<br>
 * API base path: {@code /api/v1}
 */
@RestController
@RequestMapping("/api/v1")
public class LibraryErrorLogCustomResource extends LibraryErrorLogResource {

    public LibraryErrorLogCustomResource(
        LibraryErrorLogCustomService libraryErrorLogService,
        LibraryErrorLogCustomRepository libraryErrorLogRepository,
        LibraryErrorLogQueryCustomService libraryErrorLogQueryService
    ) {
        super(libraryErrorLogService, libraryErrorLogRepository, libraryErrorLogQueryService);
    }
}
