package io.github.fossure.web.rest.v1;

import io.github.fossure.domain.LicenseNamingMapping;
import io.github.fossure.repository.LicenseNamingMappingCustomRepository;
import io.github.fossure.web.rest.LicenseNamingMappingResource;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

/**
 * Custom REST controller for managing {@link LicenseNamingMapping}
 * where changes are inserted that are different from the base class generated by the JHipster generator.<br>
 * API base path: {@code /api/v1}
 */
@RestController
@RequestMapping("/api/v1")
public class LicenseNamingMappingCustomResource extends LicenseNamingMappingResource {

    public LicenseNamingMappingCustomResource(LicenseNamingMappingCustomRepository licenseNamingMappingRepository) {
        super(licenseNamingMappingRepository);
    }
}
