package io.github.fossure.web.rest.v1;

import io.github.fossure.domain.LicensePerLibrary;
import io.github.fossure.repository.LicensePerLibraryCustomRepository;
import io.github.fossure.service.LicensePerLibraryCustomService;
import io.github.fossure.service.LicensePerLibraryQueryCustomService;
import io.github.fossure.web.rest.LicensePerLibraryResource;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

/**
 * Custom REST controller for managing {@link LicensePerLibrary}
 * where changes are inserted that are different from the base class generated by the JHipster generator.<br>
 * API base path: {@code /api/v1}
 */
@RestController
@RequestMapping("/api/v1")
public class LicensePerLibraryCustomResource extends LicensePerLibraryResource {

    public LicensePerLibraryCustomResource(
        LicensePerLibraryCustomService licensePerLibraryService,
        LicensePerLibraryCustomRepository licensePerLibraryRepository,
        LicensePerLibraryQueryCustomService licensePerLibraryQueryService
    ) {
        super(licensePerLibraryService, licensePerLibraryRepository, licensePerLibraryQueryService);
    }
}
